a = input('Fale qualquer coisa: ')
print('O tipo primitivo é:', type(a))
print('Só tem espaços?',a.isspace())
print('É um numero?',a.isnumeric())
print('É alphanumerico?',a.isalnum())
print('É alfabetico?',a.isalpha())
print('É maisculo?',a.isupper())
print('É minusculo',a.islower())
print('Esta capitalizada?',a.istitle())