nome = str(input("Qual é o seu nome? ")).strip()
print("O seu nome em maiúsculo é {}".format(nome.upper()))
print("O seu nome em minúsculo é {}".format(nome.upper()))
nletrast = (len(nome.replace(" ","")))
print("O seu nome tem {} letras" .format(nletrast))
nome1 = nome.split()
nletras1 = (len(nome1[0]))
print("O seu primeiro nome tem {} letras".format(nletras1))
#print("O seu nome tem {} letras".format(len(nome)-nome.count(" ")))